[project]
authors = ["AndreaFrederica <andreafrederica@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "wepay"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
gencode = { cmd = "python main.py"}
clean = { cmd = "python clean.py"}

build = {cmd = "python build.py build"}
build_clean = {cmd = "python build.py clean"}

[dependencies]
pip = ">=24.3.1,<25"
python = "3.12.*"

[pypi-dependencies]
opencv-python = ">=4.10.0.84, <5"
pillow = ">=11.0.0, <12"
autopep8 = ">=2.3.1, <3"
numpy = ">=2.1.2, <3"
opencv-contrib-python = ">=4.10.0.84, <5"
qrcode = ">=8.0, <9"
nuitka = ">=2.4.11, <3"
